server:
  port: 8085
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vacation
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect